const data = {
  Samsung: {
    "Galaxy A01": {
    "4GB": {
        high: {
          general: 90,
          redDot: 85,
          scope2x: 80,
          scope4x: 75,
          dpi: 400,
          pointerSpeed: "Medium"
        },
        low: {
          general: 70,
          redDot: 65,
          scope2x: 60,
          scope4x: 55,
          dpi: 320,
          pointerSpeed: "Low"
        }
      },
      "6GB": {
        high: {
          general: 93,
          redDot: 87,
          scope2x: 83,
          scope4x: 78,
          dpi: 440,
          pointerSpeed: "High"
        },
        low: {
          general: 73,
          redDot: 68,
          scope2x: 63,
          scope4x: 58,
          dpi: 360,
          pointerSpeed: "Medium"
        }
      },
      "8GB": {
        high: {
          general: 95,
          redDot: 90,
          scope2x: 86,
          scope4x: 82,
          dpi: 480,
          pointerSpeed: "High"
        },
        low: {
          general: 75,
          redDot: 70,
          scope2x: 65,
          scope4x: 60,
          dpi: 400,
          pointerSpeed: "Medium"
        }
      }
},
    "Galaxy A10": {},
    "Galaxy A10s": {},
    "Galaxy A12": {},
    "Galaxy A13": {},
    "Galaxy A14": {},
    "Galaxy A21s": {},
    "Galaxy A22": {},
    "Galaxy A23": {},
    "Galaxy A30": {},
    "Galaxy A31": {},
    "Galaxy A32": {},
    "Galaxy A33": {},
    "Galaxy A50": {},
    "Galaxy A51": {},
    "Galaxy A52": {},
    "Galaxy A53": {},
    "Galaxy A54": {},
    "Galaxy A72": {},
    "Galaxy F12": {},
    "Galaxy F13": {},
    "Galaxy F22": {},
    "Galaxy F23": {},
    "Galaxy M01": {},
    "Galaxy M02": {},
    "Galaxy M12": {},
    "Galaxy M13": {},
    "Galaxy M21": {},
    "Galaxy M31": {},
    "Galaxy M32": {},
    "Galaxy M33": {},
    "Galaxy M51": {},
    "Galaxy S10": {},
    "Galaxy S10e": {},
    "Galaxy S10 Plus": {},
    "Galaxy S20": {},
    "Galaxy S20 FE": {},
    "Galaxy S20 Plus": {},
    "Galaxy S21": {},
    "Galaxy S21 FE": {},
    "Galaxy S21 Ultra": {},
    "Galaxy S22": {},
    "Galaxy S22 Plus": {},
    "Galaxy S22 Ultra": {},
    "Galaxy S23": {},
    "Galaxy S23 Plus": {},
    "Galaxy S23 Ultra": {},
    "Galaxy S24": {},
    "Galaxy S24 Plus": {},
    "Galaxy S24 Ultra": {},
    "Galaxy S25": {},
    "Galaxy S25 Plus": {},
    "Galaxy S25 Ultra": {}
  },  
  Xiaomi: {
    "Mi 4i": {},
    "Mi 5": {},
    "Mi 5s": {},
    "Mi 6": {},
    "Mi 6X": {},
    "Mi A1": {},
    "Mi A2": {},
    "Mi A3": {},
    "Mi 8": {},
    "Mi 9": {},
    "Mi 9T": {},
    "Mi 9 SE": {},
    "Mi 10": {},
    "Mi 10i": {},
    "Mi 10T": {},
    "Mi 10T Pro": {},
    "Mi 11": {},
    "Mi 11i": {},
    "Mi 11X": {},
    "Mi 11 Ultra": {},
    "Mi 12": {},
    "Mi 12X": {},
    "Mi 12 Pro": {},
    "Mi 13": {},
    "Mi 13 Pro": {},
    "Mi 13 Ultra": {},
    "Redmi Note 7": {},
    "Redmi Note 7 Pro": {},
    "Redmi Note 8": {},
    "Redmi Note 8 Pro": {},
    "Redmi Note 9": {},
    "Redmi Note 9 Pro": {},
    "Redmi Note 10": {},
    "Redmi Note 10 Pro": {},
    "Redmi Note 11": {},
    "Redmi Note 11 Pro": {},
    "Redmi Note 12": {},
    "Redmi Note 12 Pro": {},
    "Redmi Note 13": {},
    "Redmi Note 13 Pro": {},
    "Redmi Note 13 Pro Plus": {},
    "Redmi 8": {},
    "Redmi 9": {},
    "Redmi 9 Power": {},
    "Redmi 10": {},
    "Redmi 10 Prime": {},
    "Redmi 11 Prime": {},
    "Redmi 12": {},
    "Redmi K20": {},
    "Redmi K20 Pro": {},
    "Redmi K30": {},
    "Redmi K30 Pro": {},
    "Redmi K40": {},
    "Redmi K40 Pro": {},
    "Redmi K50": {},
    "Redmi K50i": {},
    "Redmi K60": {},
    "Redmi K60 Pro": {},
    "Redmi K70": {},
    "Redmi K70 Pro": {},
    "Poco F1": {},
    "Poco F3": {},
    "Poco F4": {},
    "Poco F5": {},
    "Poco X3": {},
    "Poco X4": {},
    "Poco X5": {},
    "Poco X6": {},
    "Poco X6 Pro": {},
    "Poco M2": {},
    "Poco M3": {},
    "Poco M4 Pro": {},
    "Poco M5": {},
    "Poco M6 Pro": {}
  },
  Realme: {
    "Realme 1": {},
    "Realme 2": {},
    "Realme 2 Pro": {},
    "Realme C1": {},
    "Realme U1": {},
    "Realme 3": {},
    "Realme 3 Pro": {},
    "Realme 5": {},
    "Realme 5 Pro": {},
    "Realme XT": {},
    "Realme X": {},
    "Realme X2": {},
    "Realme X2 Pro": {},
    "Realme 6": {},
    "Realme 6 Pro": {},
    "Realme Narzo 10": {},
    "Realme Narzo 10A": {},
    "Realme 7": {},
    "Realme 7 Pro": {},
    "Realme Narzo 20": {},
    "Realme Narzo 20A": {},
    "Realme Narzo 20 Pro": {},
    "Realme X3": {},
    "Realme X3 SuperZoom": {},
    "Realme C11": {},
    "Realme C12": {},
    "Realme C15": {},
    "Realme C17": {},
    "Realme 8": {},
    "Realme 8 Pro": {},
    "Realme Narzo 30": {},
    "Realme Narzo 30A": {},
    "Realme Narzo 30 Pro": {},
    "Realme GT": {},
    "Realme GT Neo": {},
    "Realme GT Master Edition": {},
    "Realme Narzo 50": {},
    "Realme Narzo 50A": {},
    "Realme Narzo 50i": {},
    "Realme Narzo 50 Pro": {},
    "Realme 9": {},
    "Realme 9i": {},
    "Realme 9 Pro": {},
    "Realme 9 Pro+": {},
    "Realme C30": {},
    "Realme C31": {},
    "Realme C33": {},
    "Realme C35": {},
    "Realme C53": {},
    "Realme C55": {},
    "Realme Narzo N55": {},
    "Realme Narzo 60": {},
    "Realme Narzo 60 Pro": {},
    "Realme 10": {},
    "Realme 10 Pro": {},
    "Realme 10 Pro+": {},
    "Realme 11x": {},
    "Realme 11": {},
    "Realme 11 Pro": {},
    "Realme 11 Pro+": {},
    "Realme GT Neo 3": {},
    "Realme GT Neo 3T": {},
    "Realme GT Neo 5": {},
    "Realme GT 2": {},
    "Realme GT 2 Pro": {},
    "Realme GT 3": {}
  },
  Vivo: {
    "Vivo V5": {},
    "Vivo V7": {},
    "Vivo V9": {},
    "Vivo V11": {},
    "Vivo V15": {},
    "Vivo V17": {},
    "Vivo V19": {},
    "Vivo V20": {},
    "Vivo V21": {},
    "Vivo V23": {},
    "Vivo V25": {},
    "Vivo V27": {},
    "Vivo V29": {},
    "Vivo Y11": {},
    "Vivo Y12": {},
    "Vivo Y15": {},
    "Vivo Y20": {},
    "Vivo Y21": {},
    "Vivo Y22": {},
    "Vivo Y33s": {},
    "Vivo Y35": {},
    "Vivo Y50": {},
    "Vivo Y53s": {},
    "Vivo Y55": {},
    "Vivo Y73": {},
    "Vivo Y75": {},
    "Vivo Y76": {},
    "Vivo Y91": {},
    "Vivo T1": {},
    "Vivo T2": {},
    "Vivo T2x": {},
    "Vivo X50": {},
    "Vivo X60": {},
    "Vivo X60 Pro": {},
    "Vivo X70": {},
    "Vivo X70 Pro": {},
    "Vivo X80": {},
    "Vivo X80 Pro": {},
    "Vivo X90": {},
    "Vivo X90 Pro": {},
    "Vivo X100": {},
    "Vivo X100 Pro": {},
    "Vivo Y16": {},
    "Vivo Y15s": {},
    "Vivo Y12G": {},
    "Vivo V25 Pro": {}
  },
  Oppo: {
    "Oppo A1k": {},
    "Oppo A3s": {},
    "Oppo A5": {},
    "Oppo A5s": {},
    "Oppo A7": {},
    "Oppo A12": {},
    "Oppo A15": {},
    "Oppo A16": {},
    "Oppo A17": {},
    "Oppo A31": {},
    "Oppo A33": {},
    "Oppo A37": {},
    "Oppo A53": {},
    "Oppo A54": {},
    "Oppo A55": {},
    "Oppo A57": {},
    "Oppo A74": {},
    "Oppo A76": {},
    "Oppo A78": {},
    "Oppo A96": {},
    "Oppo F11": {},
    "Oppo F15": {},
    "Oppo F17": {},
    "Oppo F19": {},
    "Oppo F21 Pro": {},
    "Oppo K10": {},
    "Oppo Reno 2": {},
    "Oppo Reno 3 Pro": {},
    "Oppo Reno 4 Pro": {},
    "Oppo Reno 5": {},
    "Oppo Reno 6": {},
    "Oppo Reno 6 Pro": {},
    "Oppo Reno 7": {},
    "Oppo Reno 8": {},
    "Oppo Reno 8 Pro": {},
    "Oppo Reno 9": {},
    "Oppo Reno 10": {},
    "Oppo Reno 11": {},
    "Oppo Reno 11 Pro": {},
    "Oppo Find X2": {},
    "Oppo Find X3": {},
    "Oppo Find X5": {},
    "Oppo Find X5 Pro": {},
    "Oppo Find N2 Flip": {},
    "Oppo Find N3 Flip": {}
  },
  iQOO: {
    "iQOO Z1": {},
    "iQOO Z3": {},
    "iQOO Z5": {},
    "iQOO Z6": {},
    "iQOO Z7": {},
    "iQOO Neo 6": {},
    "iQOO Neo 7": {},
    "iQOO Neo 7 Pro": {},
    "iQOO Neo 8": {},
    "iQOO 3": {},
    "iQOO 5": {},
    "iQOO 5 Pro": {},
    "iQOO 7": {},
    "iQOO 9": {},
    "iQOO 9 SE": {},
    "iQOO 9 Pro": {},
    "iQOO 11": {},
    "iQOO 11 Pro": {},
    "iQOO 12": {},
    "iQOO 12 Pro": {}
  },
  OnePlus: {
    "OnePlus One": {},
    "OnePlus 2": {},
    "OnePlus X": {},
    "OnePlus 3": {},
    "OnePlus 3T": {},
    "OnePlus 5": {},
    "OnePlus 5T": {},
    "OnePlus 6": {},
    "OnePlus 6T": {},
    "OnePlus 7": {},
    "OnePlus 7 Pro": {},
    "OnePlus 7T": {},
    "OnePlus 7T Pro": {},
    "OnePlus 8": {},
    "OnePlus 8 Pro": {},
    "OnePlus 8T": {},
    "OnePlus 9": {},
    "OnePlus 9R": {},
    "OnePlus 9 Pro": {},
    "OnePlus 10R": {},
    "OnePlus 10 Pro": {},
    "OnePlus 10T": {},
    "OnePlus 11": {},
    "OnePlus 11R": {},
    "OnePlus 12": {},
    "OnePlus 12R": {},
    "OnePlus Nord": {},
    "OnePlus Nord CE": {},
    "OnePlus Nord CE 2": {},
    "OnePlus Nord CE 2 Lite": {},
    "OnePlus Nord 2": {},
    "OnePlus Nord 2T": {},
    "OnePlus Nord CE 3": {},
    "OnePlus Nord CE 3 Lite": {}
  },
  Apple: {
    "iPhone 5": {},
    "iPhone 5s": {},
    "iPhone 6": {},
    "iPhone 6 Plus": {},
    "iPhone 6s": {},
    "iPhone 6s Plus": {},
    "iPhone SE": {},
    "iPhone 7": {},
    "iPhone 7 Plus": {},
    "iPhone 8": {},
    "iPhone 8 Plus": {},
    "iPhone X": {},
    "iPhone XR": {},
    "iPhone XS": {},
    "iPhone XS Max": {},
    "iPhone 11": {},
    "iPhone 11 Pro": {},
    "iPhone 11 Pro Max": {},
    "iPhone 12": {},
    "iPhone 12 Mini": {},
    "iPhone 12 Pro": {},
    "iPhone 12 Pro Max": {},
    "iPhone 13": {},
    "iPhone 13 Mini": {},
    "iPhone 13 Pro": {},
    "iPhone 13 Pro Max": {},
    "iPhone 14": {},
    "iPhone 14 Plus": {},
    "iPhone 14 Pro": {},
    "iPhone 14 Pro Max": {},
    "iPhone 15": {},
    "iPhone 15 Plus": {},
    "iPhone 15 Pro": {},
    "iPhone 15 Pro Max": {},
    "iPhone 16": {},
    "iPhone 16 Plus": {},
    "iPhone 16 Pro": {},
    "iPhone 16 Pro Max": {}
  },
  Motorola: {
    "Moto E13": {},
    "Moto E20": {},
    "Moto E22": {},
    "Moto G10": {},
    "Moto G20": {},
    "Moto G22": {},
    "Moto G31": {},
    "Moto G32": {},
    "Moto G40 Fusion": {},
    "Moto G42": {},
    "Moto G51": {},
    "Moto G52": {},
    "Moto G60": {},
    "Moto G62": {},
    "Moto G71": {},
    "Moto G72": {},
    "Moto G73": {},
    "Moto Edge 20": {},
    "Moto Edge 20 Pro": {},
    "Moto Edge 30": {},
    "Moto Edge 30 Pro": {},
    "Moto Edge 30 Fusion": {},
    "Moto Edge 30 Ultra": {},
    "Moto Edge 40": {},
    "Moto Edge 40 Neo": {},
    "Moto Edge 50 Pro": {},
    "Moto Edge 50 Fusion": {}
  },
  Infinix: {
    "Infinix Smart 5": {},
    "Infinix Smart 6": {},
    "Infinix Smart 7": {},
    "Infinix Hot 10": {},
    "Infinix Hot 11": {},
    "Infinix Hot 12": {},
    "Infinix Hot 20": {},
    "Infinix Hot 30": {},
    "Infinix Zero 5G": {},
    "Infinix Zero Ultra": {},
    "Infinix Note 10": {},
    "Infinix Note 11": {},
    "Infinix Note 12": {},
    "Infinix Note 30": {},
    "Infinix Zero 30": {},
    "Infinix GT 10 Pro": {},
    "Infinix Zero X Pro": {}
  },
  Lava: {
    "Lava Agni": {},
    "Lava Agni 2": {},
    "Lava Blaze": {},
    "Lava Blaze 5G": {},
    "Lava Blaze 2": {},
    "Lava Blaze 2 5G": {},
    "Lava Blaze 3": {},
    "Lava Storm 5G": {},
    "Lava X2": {},
    "Lava Yuva": {},
    "Lava Yuva 2": {},
    "Lava Yuva 2 Pro": {},
    "Lava Yuva 3": {},
    "Lava Yuva 3 Pro": {},
    "Lava Z1": {},
    "Lava Z2": {},
    "Lava Z3": {},
    "Lava Z4": {},
    "Lava Z6": {}
  },
  Tecno: {
    "Tecno Camon 17": {},
    "Tecno Camon 18": {},
    "Tecno Camon 19": {},
    "Tecno Camon 20": {},
    "Tecno Camon 20 Pro": {},
    "Tecno Pova 2": {},
    "Tecno Pova 3": {},
    "Tecno Pova 4": {},
    "Tecno Pova 5": {},
    "Tecno Spark 7": {},
    "Tecno Spark 8": {},
    "Tecno Spark 9": {},
    "Tecno Spark 10": {},
    "Tecno Phantom X": {},
    "Tecno Phantom X2": {},
    "Tecno Phantom V Fold": {},
    "Tecno Pop 5": {},
    "Tecno Pop 6": {},
    "Tecno Pop 7": {}
  },
  Asus: {
    "Asus ROG Phone": {},
    "Asus ROG Phone 2": {},
    "Asus ROG Phone 3": {},
    "Asus ROG Phone 5": {},
    "Asus ROG Phone 5s": {},
    "Asus ROG Phone 6": {},
    "Asus ROG Phone 6 Pro": {},
    "Asus ROG Phone 7": {},
    "Asus ROG Phone 7 Ultimate": {},
    "Asus Zenfone 6": {},
    "Asus Zenfone 7": {},
    "Asus Zenfone 8": {},
    "Asus Zenfone 8 Flip": {},
    "Asus Zenfone 9": {},
    "Asus Zenfone 10": {}
  },
  Huawei: {
    "Huawei P20": {},
    "Huawei P20 Pro": {},
    "Huawei P30": {},
    "Huawei P30 Pro": {},
    "Huawei P40": {},
    "Huawei P40 Pro": {},
    "Huawei P50": {},
    "Huawei P50 Pro": {},
    "Huawei P60": {},
    "Huawei P60 Pro": {},
    "Huawei Mate 20": {},
    "Huawei Mate 20 Pro": {},
    "Huawei Mate 30": {},
    "Huawei Mate 30 Pro": {},
    "Huawei Mate 40": {},
    "Huawei Mate 40 Pro": {},
    "Huawei Nova 3": {},
    "Huawei Nova 5T": {},
    "Huawei Nova 7": {},
    "Huawei Nova 8": {},
    "Huawei Nova 9": {},
    "Huawei Nova 10": {},
    "Huawei Nova 11": {},
    "Huawei Y7": {},
    "Huawei Y8": {},
    "Huawei Y9": {},
    "Huawei Y9 Prime": {},
    "Huawei Y9s": {}
  },
  LG: {
    "LG G4": {},
    "LG G5": {},
    "LG G6": {},
    "LG G7 ThinQ": {},
    "LG G8 ThinQ": {},
    "LG G8X": {},
    "LG V20": {},
    "LG V30": {},
    "LG V40": {},
    "LG V50": {},
    "LG V60": {},
    "LG Velvet": {},
    "LG Wing": {},
    "LG Q6": {},
    "LG Q7": {},
    "LG Q60": {},
    "LG Stylo 5": {},
    "LG Stylo 6": {},
    "LG W10": {},
    "LG W30": {},
    "LG W41": {}
  },
  Sony: {
    "Sony Xperia XZ1": {},
    "Sony Xperia XZ2": {},
    "Sony Xperia XZ3": {},
    "Sony Xperia 1": {},
    "Sony Xperia 1 II": {},
    "Sony Xperia 1 III": {},
    "Sony Xperia 1 IV": {},
    "Sony Xperia 1 V": {},
    "Sony Xperia 5": {},
    "Sony Xperia 5 II": {},
    "Sony Xperia 5 III": {},
    "Sony Xperia 5 IV": {},
    "Sony Xperia 10": {},
    "Sony Xperia 10 II": {},
    "Sony Xperia 10 III": {},
    "Sony Xperia 10 IV": {},
    "Sony Xperia 10 V": {},
    "Sony Xperia L4": {},
    "Sony Xperia L3": {}
  },
  Poco: {
    "Poco F1": {},
    "Poco F2 Pro": {},
    "Poco F3": {},
    "Poco F4": {},
    "Poco F5": {},
    "Poco X2": {},
    "Poco X3": {},
    "Poco X3 Pro": {},
    "Poco X4": {},
    "Poco X4 Pro": {},
    "Poco X5": {},
    "Poco X5 Pro": {},
    "Poco X6": {},
    "Poco X6 Pro": {},
    "Poco M2": {},
    "Poco M2 Pro": {},
    "Poco M3": {},
    "Poco M3 Pro": {},
    "Poco M4": {},
    "Poco M4 Pro": {},
    "Poco M5": {},
    "Poco M5s": {},
    "Poco M6": {},
    "Poco M6 Pro": {}
  },
  Redmi: {
    "Redmi 4": {},
    "Redmi 4A": {},
    "Redmi 5": {},
    "Redmi 5A": {},
    "Redmi 6": {},
    "Redmi 6A": {},
    "Redmi 7": {},
    "Redmi 7A": {},
    "Redmi 8": {},
    "Redmi 8A": {},
    "Redmi 9": {},
    "Redmi 9A": {},
    "Redmi 9i": {},
    "Redmi 9 Prime": {},
    "Redmi 9 Power": {},
    "Redmi 10": {},
    "Redmi 10 Prime": {},
    "Redmi 11 Prime": {},
    "Redmi 12": {},
    "Redmi Note 4": {},
    "Redmi Note 5": {},
    "Redmi Note 5 Pro": {},
    "Redmi Note 6 Pro": {},
    "Redmi Note 7": {},
    "Redmi Note 7 Pro": {},
    "Redmi Note 8": {},
    "Redmi Note 8 Pro": {},
    "Redmi Note 9": {},
    "Redmi Note 9 Pro": {},
    "Redmi Note 10": {},
    "Redmi Note 10 Pro": {},
    "Redmi Note 11": {},
    "Redmi Note 11 Pro": {},
    "Redmi Note 12": {},
    "Redmi Note 12 Pro": {},
    "Redmi Note 13": {},
    "Redmi Note 13 Pro": {},
    "Redmi Note 13 Pro+": {},
    "Redmi K20": {},
    "Redmi K20 Pro": {},
    "Redmi K30": {},
    "Redmi K30 Pro": {},
    "Redmi K40": {},
    "Redmi K40 Pro": {},
    "Redmi K50": {},
    "Redmi K50i": {},
    "Redmi K60": {},
    "Redmi K60 Pro": {},
    "Redmi K70": {},
    "Redmi K70 Pro": {}
  },
  Other: {
  }
};